### ISSUE TITLE
Four unbuilt projection kinds have a reason no command ever prints

### ISSUE THREAD

**Issue by jameswbaxter** [headwater-ai/headwater#596]
## ELI5

The tool that generates files can produce twelve kinds of file. Five of those kinds it does not produce, and for each of the five its code carries a written sentence saying what is missing. Only one of those five sentences ever reached a person: the tool prints a "what I did not write, and why" section, and a kind only appeared there if this particular project asked for that kind of file. Nobody had ever asked for four of them, so their sentences had never been printed anywhere. Fixed means a person can run one command and read all five reasons, whether or not their project asked for those files.

Filed as the remainder of #576, which repaired the specification prose that stated four of those five kinds as built. #576 shipped a Rust test that holds the prose against the engine, so the sentence is now guarded. This issue is about the *verb*, not the prose, and it is a behavior decision rather than a correction.

## What happens today

`engine/crates/generate/src/lib.rs` carries `pub fn unbuilt(kind: Kind) -> Option<&'static str>`. It answers `Some(reason)` for five of the twelve projection kinds: `relation_view`, `agent_rules`, `template`, `transcription` and `coverage_report`.

Only two routes put a reason in front of a reader.

- `plan()` pushes an `Unwritten` entry for a **declared** kind with no emitter. This corpus declares no `relation_view`, no `agent_rules`, no `template` and no `transcription`, so those four reasons reach nobody here, and they reach nobody in any corpus that declares no instance of them.
- `engine_defined()` pushes the `coverage_report` entry unconditionally, because the register is engine-defined and needs no declaration.

Measured on `main` before the fix: `engine/crates/generate/fixtures/generate.record` contained `coverage_report the register` seven times and **zero** occurrences of `relation_view`, `agent_rules`, `template` or `transcription`. The doc comment on `unbuilt` says the posture is that "a surface the specification lists and this engine does not implement is reported as that, and never as an empty result". For four of the five kinds, nothing reported it.

The consequence for an adopter: a taxonomy author who reads spec 6, sees `relation_view` in the declarable ten, declares one, and runs `headwater generate` gets a line naming the reason. An adopter who has not declared one, and who wants to know before they write the declaration whether the emitter exists, has no command that tells them.

## The question, before the work

Should `headwater generate --check` report a kind no taxonomy asked for? A reasonable answer is no, because a verb that reports on every unbuilt kind on every run adds five lines a reader has already read. An equally reasonable answer is a separate surface — `headwater explain`, or a flag — that answers "what can this engine emit" without changing what a run of `generate` prints.

That is why this is filed rather than folded into #576. It is a behavior decision, and it moves `engine/crates/generate/fixtures/generate.record` in **every one of its seven scenarios**, because the "what this verb does not write, and why" section appears seven times in that file.

## Done when

- [x] A decision record or an issue comment states whether `generate --check` reports an undeclared unbuilt kind, or whether a different surface answers it. The ruling names which, and why.
- [x] Whichever surface the ruling names prints the reason `unbuilt()` gives, for each of the five kinds it answers `Some` for, over a corpus that declares an instance of none of them.
- [x] `engine/crates/generate/fixtures/generate.record` is re-blessed and the diff is exactly the new lines, in every scenario the section appears in.
- [x] The interface contract for the verb the ruling names states the new behavior.

## What this does not cover

Building `relation_view`, `agent_rules`, `template` or `transcription`. Each waits on a document that does not exist, and #576 left them under `waits` in spec 6's projection-kinds block with that reason stated.

## One more instrument gap, recorded here because one mechanism could hold both

`docs/spec/02-taxonomy-model.md` quotes `headwater export --format skos`'s refusal verbatim in a fenced block (#421's work). The block is byte-exact today — it was re-run on `0efe2ba` and matches. **Nothing holds it there.** `grep -rn "waits on a named external consumer"` returns the spec 2 block, `engine/crates/generate/src/export.rs:188`, and one review document. No test, no fixture and no shell suite compares them. #576 shipped `engine/crates/generate/tests/spec_six_projections.rs`, which holds spec 6's coverage-report quote against `unbuilt(Kind::CoverageReport)` by string containment. The same shape would hold spec 2's block against the export refusal, and it is a small file.

*Filed as the remainder of #576. Refs #576.*

---

*Body corrected 2026-09-07, after PR #612 merged. The count was wrong throughout: this issue said **three** unbuilt projection kinds went unprinted, and there were **four** — `relation_view`, `agent_rules`, `template` and `transcription`. The body named only the first three and omitted `transcription` everywhere, including in the ELI5, in the `plan()` bullet, in the `generate.record` measurement and in the scope note. Five kinds return `Some` from `unbuilt()`; only `coverage_report` ever printed, so four reasons were unreachable, not three. The title was corrected from "Three" to "Four" and is otherwise unchanged, so a search on the rest of the sentence still finds this issue. The Done-when boxes were ticked in the same edit; the comment below says which clause each of #595 and #612 carried.*

**Comment by jameswbaxter** [comment]
Labeled `adopter-blocking` by product-owner review 2026-09-07. R1's Done-when names this clause directly: "no specification part states as built an `export` target or a projection kind that `headwater export --help` or `headwater generate` reports as unbuilt." An adopter who runs the command the specification states in the present tense gets nothing, so the release bar cannot be met while this is open.

**Comment by jameswbaxter** [comment]
## The ruling, recorded here rather than as a decision record

Done-when clause 1 permits a decision record **or an issue comment**. This is the issue comment, and it is deliberate: a decision record would mint an `HW-DR` number, #421 is being built in parallel and may mint one from the same `main`, and `headwater new` allocates by reading one tree. The claim store from #583 turns that into an `add/add` conflict rather than a silent duplicate, and the cheaper answer is to not mint at all.

**`headwater generate` reports every kind `unbuilt()` gives a reason for, whether or not a taxonomy declared one.** The reason is a property of this engine rather than of the reader's corpus. The question an adopter asks — "does this emitter exist" — is asked before the declaration is written, not after, so the answer cannot sit behind the declaration of the kind it is the reason for.

### The count is four, not three

The body names three unreachable kinds and omits `transcription`. `unbuilt()` answers `Some` for five kinds. `coverage_report` is engine-defined and printed on every run, and the other four — `relation_view`, `agent_rules`, `template`, `transcription` — are declarable and were reached only where a declaration named them. Each of the four occurred 0 times in `engine/crates/generate/fixtures/generate.record`, the recorded output of seven runs, against 7 occurrences of `coverage_report`.

### The alternatives, and why neither was taken

A separate surface was rejected. `headwater explain` takes a `path|identifier` and refuses `--format`, so a topic argument is a new grammar, and a new flag on `generate` moves six files for a section that already exists under exactly the right heading, *what this verb does not write, and why*. The counter-argument the body raises — five lines a reader has already read, on every run — is accepted as the cost. Four of those five lines were unreachable, and a reason nobody can reach is worse than a reason repeated.

### What carries it

`plan()` pushes an `Unwritten` for every declarable kind `unbuilt()` gives a reason and no declaration named, in `Kind::ALL` order so two plans over one tree hold the same bytes. The undeclared entries read `no declaration names one` where a declared one reads its output path. `engine/crates/generate/tests/spec_six_projections.rs` holds the whole set against one run over a corpus declaring no projection at all, deriving the set from `Kind::ALL.iter().filter_map(unbuilt)` rather than from a list typed in the test.

**Comment by jameswbaxter** [comment]
## Discharged by #612, clause by clause

This issue was already closed by PR #612 (squashed to `8e0f6da` on `main`, "Print the reason of every unbuilt projection kind, declared or not"). This comment records which clause each merge carried, because two merges were involved and the split is not obvious from the closing reference alone.

**What #595 carried, before this work started.** #595 (commit `46454c9`) is the precondition rather than a clause. It made `generate::unbuilt` public, gave it an `Option` return, moved the register's true reason into its own arm so `engine_defined()` reads one copy, and wrote spec 6's `runs`/`waits` block naming which projection kinds this engine emits. It met none of the four clauses below on its own — every one of them is about a reason reaching a reader — but clause 2 quantifies over "the five kinds it answers `Some` for", and that reason table is what #595 built. It also repaired the spec 6 line that R1's bar names as an offender, which matters for the label comment below.

**Clause 1 — the ruling.** Met by the [ruling comment on this issue](https://github.com/headwater-ai/headwater/issues/596#issuecomment-5562802450), which clause 1 permits in place of a decision record. The ruling: `headwater generate` reports every kind `unbuilt()` gives a reason for, declared or not, because the reason is a property of this engine rather than of the reader's corpus. The comment states why a separate surface and a new flag were both rejected.

**Clause 2 — the reason reaches a reader over a corpus declaring none of them.** Met by #612. `plan()` gained `undeclared()`, which pushes an `Unwritten` for every declarable kind `unbuilt()` gives a reason and no declaration named, in `Kind::ALL` order so two plans over one tree hold the same bytes. `engine/crates/generate/tests/spec_six_projections.rs` gained `every_unbuilt_reason_reaches_a_reader_of_a_corpus_that_declares_none`, which derives its population from `Kind::ALL.into_iter().filter_map(unbuilt)` rather than from a list typed into the test. It was watched failing first, naming exactly the four kinds this issue's corrected body names.

A second case, `a_kind_a_declaration_named_is_reported_once_and_not_twice`, was added after verification found the anti-doubling guard was an empty arm. It declares two of the four through `Projections::read` and leaves two undeclared, so both routes run in one report, and it asserts every reason appears exactly once. With the guard deleted it reddens, naming `[("relation_view", 2), ("template", 2)]`.

**Clause 3 — the record re-blessed, the diff exactly the new lines.** Met by #612. `engine/crates/generate/fixtures/generate.record`: 56 insertions, 0 deletions, 7 hunks, every hunk anchored on a *what this verb does not write, and why* context line. Eight distinct added lines each occurring exactly 7 times — four kind lines and four reason lines — for 28 entries of 2 lines each. Re-derived independently by verification and matched exactly.

**Clause 4 — the interface contract states the new behavior.** Met by #612. `docs/interfaces/headwater-generate.md` gained a paragraph in Description and moved `last_verified` to `2026-09-07`. Verification injected a British spelling, a retired term and a hard wrap into the new prose of both that file and spec 6 and got 71 findings with 2 errors and exit 1, against 68 warns and exit 0 clean, so the added prose sits on shelves the rules reach.

**One number outside the clauses.** `engine/crates/generate/tests/fixtures.rs:671` asserted `plan.unwritten.len() == 3` over this repository's own corpus and now asserts 7: one empty shelf, one `probe_result` with no source, the four newly reachable kinds, and `coverage_report`. That assertion is a hand-kept measurement rather than a recorded comparison, so `HEADWATER_BLESS=1` did not move it; see the next comment.

**Comment by jameswbaxter** [comment]
## `adopter-blocking` removed, and no label put in its place

The label was applied [here](https://github.com/headwater-ai/headwater/issues/596#issuecomment-5562722774) on the strength of one R1 Done-when clause: "no specification part states as built an `export` target or a projection kind that `headwater export --help` or `headwater generate` reports as unbuilt." That clause does not describe this issue.

**The clause is about a claim in the wrong direction.** It refuses a specification part that states as *built* what the binary reports as *unbuilt*. This issue is the opposite direction: it is a reachability repair, and it asks that a reason the binary already holds reaches a reader who did not declare the kind. No specification part was stating anything as built here. The old spec 6 line 139 said `coverage_report` was the one waiting kind a run names, which is a false claim about what a run prints, not a claim that an unbuilt kind is built.

**The clause's own offenders were named, and one is already repaired.** R1's "what carries each clause" paragraph names exactly two: "#421 and spec 6 line 114". #595 repaired line 114. #421 is open and carries the other half. The clause is therefore fully carried without this issue, and it was carried without this issue when the label was applied.

**It is not `self-audit` either, so nothing replaces the label.** The value rule asks for a reader who is not this repository, and this work has one: an adopter deciding whether to declare a `relation_view` now learns the emitter does not exist *before* writing the declaration rather than after. That is a real outside gain. It is simply not a gain the release bar waits on, which is what `adopter-blocking` means.

**How the wrong label got here, because the mechanism will do it again.** It came from a mechanical pass that matched issue text against milestone bar text. That pass reads what a bar says and what an issue says; it cannot read the tree, so it cannot see that a bar clause was already met by a merge. The same pass put the same stale label on #421 for the same reason, and the parent removed it there. An issue whose subject shares vocabulary with a bar clause is not an issue that clause waits on.

Removed rather than re-justified on another clause: no other R1 clause names this work either. The issue stays in R1 as a completed member.

**Comment by jameswbaxter** [comment]
## The new test's population is hand-kept, and the register is owed an entry

Recorded here rather than filed as an issue. By the value rule its only beneficiary is this engine's own correctness, so it belongs in `docs/spec/13-open-obligations.md`. **That entry is owed and not yet written** — scaffolding one needs a built engine and moves three blessed fixtures, so it is queued as work of its own. This comment is the evidence, so it has a public home in the meantime.

### What was measured, by adding a variant rather than by reading

Verification added a thirteenth `Kind` variant to `engine/crates/generate/src/lib.rs` and changed nothing else.

**Stage A — the good half.** `cargo build -p headwater-generate` failed with exactly two `error[E0004]`s and nothing else: one in `Kind::name` and one in `unbuilt`. So `unbuilt()`'s `match` is **genuinely exhaustive**, proven rather than assumed. The reason *table* cannot go stale silently.

**Stage B — the finding.** Satisfying only those two arms is what an author following the compiler would do. `Kind::ALL` was left alone. `cargo test -p headwater-generate` then returned **exit 0**, 8 targets ok, 0 failed, with #612's new case `every_unbuilt_reason_reaches_a_reader_of_a_corpus_that_declares_none` passing.

That case derives its population from `Kind::ALL.into_iter().filter_map(unbuilt)`, and `Kind::ALL` is a hand-kept array. **So the test inherits the blindness it was written to cure**, for the one input class that matters: a kind added later. A thirteenth kind carrying a reason no run will ever print passes the whole suite. The `Kind::ALL` doc comment already says this in words; documented is not held.

### Two adjacent holes in the same shape

- `Kind::declarable()` is `!matches!(self, CoverageReport | CorpusDescriptor)`, so a new variant is **declarable by default**, with no author decision recorded. This is the `matches!` shape #610 found in `Emitter::is_built`.
- `Kind::DECLARABLE` is a **second** hand-kept array, `[Kind; 10]`, and `Kind::parse` reads only it. A new kind that is `declarable() == true` is still unparseable from a taxonomy: declarable in one statement, unreachable in another, and nothing compares the two.

### How big the class is, engine-wide

**9 hand-kept `ALL` arrays across 6 crates**: `Kind::ALL` and `Kind::DECLARABLE` in `generate/src/lib.rs`, `Emitter::ALL` in `generate/src/profile.rs`, four in `probe/src/lib.rs` (`Category`, `Expectation`, `Tier`, `Arm`), `Format::ALL` in `adapter/src/lib.rs`, `Class::ALL` in `sweep/src/lib.rs`, and `Shell::ALL` in `cli/src/lib.rs`, which is a slice and so declares not even a length. Only the two in `generate/src/lib.rs` were variant-tested; the rest carry the same exposure by construction, an array literal whose completeness no `match` holds.

**50 `assert_eq!(…len(), N)` literals** with `N >= 2` across `engine/crates/*/src` and `engine/crates/*/tests`, **29 of them in `tests/`**. Most are over a fixture corpus the test itself builds, where a literal is the correct assertion. The dangerous subset is a literal over a population that grows independently of the test. Two clear ones: `engine/crates/generate/tests/fixtures.rs:671`, which this work moved from 3 to 7 and which `HEADWATER_BLESS=1` could not move because it is a measurement rather than a recorded comparison; and `engine/crates/check/tests/fixtures.rs:1705`, `assert_eq!(declared.len(), 23, "one instance per typed document")`, where it was not established whether the 23 is over this repository's corpus or a scratch one.

**Nothing was fixed.** Every experiment above was restored and `git status` was checked clean rather than assumed.
